In [54]:
import pandas as pd
from pathlib import Path
import numpy as np

In [55]:
base_dir = Path().resolve().parents[1]
print(f"Base directory: {base_dir}")
interim_dir = base_dir /"Patricia-Promise-Immo"/"data" / "interim"
print(f"Interim directory: {interim_dir}")
data_no_empty_path = interim_dir / "all_immo_no_empty.csv"

df = pd.read_csv(f"{data_no_empty_path}", on_bad_lines='skip', low_memory=False, sep=',', dtype={'Code postal':str, 'Valeur fonciere':np.float64})
df

Base directory: D:\ProjectFolderDevAI_2025-2026\Immo_project
Interim directory: D:\ProjectFolderDevAI_2025-2026\Immo_project\Patricia-Promise-Immo\data\interim

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,...,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre
0,1,02/01/2024,Vente,346.5,NaN,NaN,NaN,B020,LE DELIVRE,1230,...,124.0,465.0,27.0,591.0,394.0,910.0,45.955,5.530,45.953,5.537
1,2,03/01/2024,Vente,10000.0,NaN,NaN,NaN,B007,CHEVRY DESSOUS,1170,...,2261.0,579.0,391.0,496.0,457.0,580.0,46.280,6.036,46.283,6.047
2,1,08/01/2024,Vente,249000.0,NaN,NaN,NaN,B086,PIN HAMEAU,1290,...,1299.0,1029.0,126.0,186.0,173.0,210.0,46.248,4.890,46.247,4.899
3,1,03/01/2024,Vente,329500.0,29.0,NaN,PL,0500,DU JURA,1170,...,13078.0,3186.0,410.0,949.0,532.0,1614.0,46.334,6.058,46.347,6.046
4,1,03/01/2024,Vente,329500.0,9001.0,NaN,PL,0500,DU JURA,1170,...,13078.0,3186.0,410.0,949.0,532.0,1614.0,46.334,6.058,46.347,6.046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1,22/03/2024,Vente,131850.0,6.0,B,AV,0067,DE L'AERODROME DE MONTAUDR,31400,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999996,1,22/03/2024,Vente,131850.0,6.0,NaN,AV,0067,DE L'AERODROME DE MONTAUDR,31400,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999997,1,13/03/2024,Vente,300000.0,42.0,NaN,RUE,2424,DE CUGNAUX,31300,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999998,1,13/03/2024,Vente,300000.0,42.0,NaN,RUE,2424,DE CUGNAUX,31300,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999999,1,13/03/2024,Vente,300000.0,42.0,NaN,RUE,2424,DE CUGNAUX,31300,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432

In [56]:
df['Type local'] = df['Type local'].replace({
    'Dépendance': 1,
    'Maison': 2,
    'Appartement': 3
})

In [57]:
# -- Filtrer seulement les ventes (si la colonne existe)
if "Nature mutation" in df.columns:
    df = df[df["Nature mutation"]=="Vente"]
df

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,...,population,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre
0,1,02/01/2024,Vente,346.5,NaN,NaN,NaN,B020,LE DELIVRE,1230,...,124.0,465.0,27.0,591.0,394.0,910.0,45.955,5.530,45.953,5.537
1,2,03/01/2024,Vente,10000.0,NaN,NaN,NaN,B007,CHEVRY DESSOUS,1170,...,2261.0,579.0,391.0,496.0,457.0,580.0,46.280,6.036,46.283,6.047
2,1,08/01/2024,Vente,249000.0,NaN,NaN,NaN,B086,PIN HAMEAU,1290,...,1299.0,1029.0,126.0,186.0,173.0,210.0,46.248,4.890,46.247,4.899
3,1,03/01/2024,Vente,329500.0,29.0,NaN,PL,0500,DU JURA,1170,...,13078.0,3186.0,410.0,949.0,532.0,1614.0,46.334,6.058,46.347,6.046
4,1,03/01/2024,Vente,329500.0,9001.0,NaN,PL,0500,DU JURA,1170,...,13078.0,3186.0,410.0,949.0,532.0,1614.0,46.334,6.058,46.347,6.046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1,22/03/2024,Vente,131850.0,6.0,B,AV,0067,DE L'AERODROME DE MONTAUDR,31400,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999996,1,22/03/2024,Vente,131850.0,6.0,NaN,AV,0067,DE L'AERODROME DE MONTAUDR,31400,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999997,1,13/03/2024,Vente,300000.0,42.0,NaN,RUE,2424,DE CUGNAUX,31300,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999998,1,13/03/2024,Vente,300000.0,42.0,NaN,RUE,2424,DE CUGNAUX,31300,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432
999999,1,13/03/2024,Vente,300000.0,42.0,NaN,RUE,2424,DE CUGNAUX,31300,...,504078.0,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432

In [58]:
df.fillna(0.0, inplace=True)

C:\Users\PATRICIA\AppData\Local\Temp\ipykernel_11984\327117627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0.0, inplace=True)

In [59]:
# Calcul de la surface totale
df['surface_total']=df["Surface Carrez du 1er lot"]+df["Surface Carrez du 2eme lot"]+ df["Surface Carrez du 3eme lot"]+df["Surface Carrez du 4eme lot"]+df["Surface Carrez du 5eme lot"]
df

C:\Users\PATRICIA\AppData\Local\Temp\ipykernel_11984\1663961423.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['surface_total']=df["Surface Carrez du 1er lot"]+df["Surface Carrez du 2eme lot"]+ df["Surface Carrez du 3eme lot"]+df["Surface Carrez du 4eme lot"]+df["Surface Carrez du 5eme lot"]

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,...,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,surface_total
0,1,02/01/2024,Vente,346.5,0.0,0.0,0.0,B020,LE DELIVRE,1230,...,465.0,27.0,591.0,394.0,910.0,45.955,5.530,45.953,5.537,0.00
1,2,03/01/2024,Vente,10000.0,0.0,0.0,0.0,B007,CHEVRY DESSOUS,1170,...,579.0,391.0,496.0,457.0,580.0,46.280,6.036,46.283,6.047,0.00
2,1,08/01/2024,Vente,249000.0,0.0,0.0,0.0,B086,PIN HAMEAU,1290,...,1029.0,126.0,186.0,173.0,210.0,46.248,4.890,46.247,4.899,0.00
3,1,03/01/2024,Vente,329500.0,29.0,0.0,PL,0500,DU JURA,1170,...,3186.0,410.0,949.0,532.0,1614.0,46.334,6.058,46.347,6.046,0.00
4,1,03/01/2024,Vente,329500.0,9001.0,0.0,PL,0500,DU JURA,1170,...,3186.0,410.0,949.0,532.0,1614.0,46.334,6.058,46.347,6.046,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1,22/03/2024,Vente,131850.0,6.0,B,AV,0067,DE L'AERODROME DE MONTAUDR,31400,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,0.00
999996,1,22/03/2024,Vente,131850.0,6.0,0.0,AV,0067,DE L'AERODROME DE MONTAUDR,31400,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,0.00
999997,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23
999998,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,0.00
999999,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23

In [60]:
# Ne garde que les surface strictement superieur à zéro
df=df[df.surface_total>0.0] 
df

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,...,superficie_hectare,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,surface_total
100,1,04/01/2024,Vente,105000.0,269.0,0.0,RUE,0240,DE LA MAIRIE,1960,...,2451.0,49.0,253.0,222.0,269.0,46.157,5.146,46.149,5.142,64.01
101,1,04/01/2024,Vente,105000.0,269.0,0.0,RUE,0240,DE LA MAIRIE,1960,...,2451.0,49.0,253.0,222.0,269.0,46.157,5.146,46.149,5.142,64.01
118,1,09/01/2024,Vente,309700.0,2.0,0.0,0.0,B055,LA GASSE,1390,...,2019.0,95.0,286.0,225.0,311.0,45.920,4.882,45.922,4.886,81.46
125,1,05/01/2024,Vente,565423.0,537.0,0.0,AV,0507,MARCEL ANTHONIOZ,1220,...,3374.0,300.0,810.0,464.0,1447.0,46.358,6.136,46.376,6.116,85.82
130,1,10/01/2024,Vente,110000.0,32.0,0.0,RUE,0509,DE SAVOIE,1200,...,1544.0,1055.0,554.0,330.0,1606.0,46.108,5.826,46.107,5.832,45.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999924,1,09/04/2024,Vente,65000.0,18.0,0.0,RUE,3821,DU GENERAL GIRAUD,31200,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,34.38
999967,1,12/03/2024,Vente,64500.0,46.0,0.0,BD,2600,DEODAT DE SEVERAC,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,21.91
999990,1,14/03/2024,Vente,191450.0,65.0,0.0,AV,5308,DE LOMBEZ,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.73
999997,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23
999999,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,11809.0,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23

In [61]:
# Calcul du prix au m2
df['prixm2']=df["Valeur fonciere"]/df.surface_total
df

C:\Users\PATRICIA\AppData\Local\Temp\ipykernel_11984\2160626705.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['prixm2']=df["Valeur fonciere"]/df.surface_total

,No disposition,Date mutation,Nature mutation,Valeur fonciere,No voie,B/T/Q,Type de voie,Code voie,Voie,Code postal,...,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,surface_total,prixm2
100,1,04/01/2024,Vente,105000.0,269.0,0.0,RUE,0240,DE LA MAIRIE,1960,...,49.0,253.0,222.0,269.0,46.157,5.146,46.149,5.142,64.01,1640.368692
101,1,04/01/2024,Vente,105000.0,269.0,0.0,RUE,0240,DE LA MAIRIE,1960,...,49.0,253.0,222.0,269.0,46.157,5.146,46.149,5.142,64.01,1640.368692
118,1,09/01/2024,Vente,309700.0,2.0,0.0,0.0,B055,LA GASSE,1390,...,95.0,286.0,225.0,311.0,45.920,4.882,45.922,4.886,81.46,3801.865946
125,1,05/01/2024,Vente,565423.0,537.0,0.0,AV,0507,MARCEL ANTHONIOZ,1220,...,300.0,810.0,464.0,1447.0,46.358,6.136,46.376,6.116,85.82,6588.475880
130,1,10/01/2024,Vente,110000.0,32.0,0.0,RUE,0509,DE SAVOIE,1200,...,1055.0,554.0,330.0,1606.0,46.108,5.826,46.107,5.832,45.67,2408.583315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999924,1,09/04/2024,Vente,65000.0,18.0,0.0,RUE,3821,DU GENERAL GIRAUD,31200,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,34.38,1890.634090
999967,1,12/03/2024,Vente,64500.0,46.0,0.0,BD,2600,DEODAT DE SEVERAC,31300,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,21.91,2943.861251
999990,1,14/03/2024,Vente,191450.0,65.0,0.0,AV,5308,DE LOMBEZ,31300,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.73,3205.256990
999997,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23,5065.000844
999999,1,13/03/2024,Vente,300000.0,42.0,0.0,RUE,2424,DE CUGNAUX,31300,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23,5065.000844

In [62]:
# Séparation propre les dtypes 
num_cols = df.select_dtypes(include=["number"]).columns.tolist()

num_cols

['No disposition',
 'Valeur fonciere',
 'No voie',
 'Code commune',
 'Prefixe de section',
 'No plan',
 'Surface Carrez du 1er lot',
 'Surface Carrez du 2eme lot',
 'Surface Carrez du 3eme lot',
 'Surface Carrez du 4eme lot',
 '5eme lot',
 'Surface Carrez du 5eme lot',
 'Nombre de lots',
 'Code type local',
 'Surface reelle bati',
 'Nombre pieces principales',
 'Surface terrain',
 'population',
 'superficie_hectare',
 'densite',
 'altitude_moyenne',
 'altitude_minimale',
 'altitude_maximale',
 'latitude_mairie',
 'longitude_mairie',
 'latitude_centre',
 'longitude_centre',
 'surface_total',
 'prixm2']

In [63]:
obj_cols = df.select_dtypes(include=["object"]).columns.tolist()
obj_cols

['Date mutation',
 'Nature mutation',
 'B/T/Q',
 'Type de voie',
 'Code voie',
 'Voie',
 'Code postal',
 'Commune',
 'Code departement',
 'Section',
 'No Volume',
 '1er lot',
 '2eme lot',
 '3eme lot',
 '4eme lot',
 'Type local',
 'Nature culture',
 'Nature culture speciale',
 'Code INSEE',
 'code_insee']

In [64]:
# Remplissage des NaN seulement sur les colonnes numériques avec 0
#df[num_cols] = df[num_cols].fillna(0)
#df

In [65]:
# Construction du dataset "features" numérique en enlèvant les objets
df_final = df.drop(columns=obj_cols, errors="ignore")
df_final

,No disposition,Valeur fonciere,No voie,Code commune,Prefixe de section,No plan,Surface Carrez du 1er lot,Surface Carrez du 2eme lot,Surface Carrez du 3eme lot,Surface Carrez du 4eme lot,...,densite,altitude_moyenne,altitude_minimale,altitude_maximale,latitude_mairie,longitude_mairie,latitude_centre,longitude_centre,surface_total,prixm2
100,1,105000.0,269.0,336,0.0,231,0.00,64.01,0.0,0.0,...,49.0,253.0,222.0,269.0,46.157,5.146,46.149,5.142,64.01,1640.368692
101,1,105000.0,269.0,336,0.0,231,0.00,64.01,0.0,0.0,...,49.0,253.0,222.0,269.0,46.157,5.146,46.149,5.142,64.01,1640.368692
118,1,309700.0,2.0,105,0.0,368,81.46,0.00,0.0,0.0,...,95.0,286.0,225.0,311.0,45.920,4.882,45.922,4.886,81.46,3801.865946
125,1,565423.0,537.0,143,0.0,714,85.82,0.00,0.0,0.0,...,300.0,810.0,464.0,1447.0,46.358,6.136,46.376,6.116,85.82,6588.475880
130,1,110000.0,32.0,33,0.0,740,45.67,0.00,0.0,0.0,...,1055.0,554.0,330.0,1606.0,46.108,5.826,46.107,5.832,45.67,2408.583315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999924,1,65000.0,18.0,555,831.0,180,34.38,0.00,0.0,0.0,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,34.38,1890.634090
999967,1,64500.0,46.0,555,828.0,304,21.91,0.00,0.0,0.0,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,21.91,2943.861251
999990,1,191450.0,65.0,555,844.0,46,59.73,0.00,0.0,0.0,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.73,3205.256990
999997,1,300000.0,42.0,555,828.0,60,59.23,0.00,0.0,0.0,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23,5065.000844
999999,1,300000.0,42.0,555,828.0,60,59.23,0.00,0.0,0.0,...,4269.0,148.0,115.0,263.0,43.605,1.444,43.596,1.432,59.23,5065.000844

In [66]:
# Nettoyage éventuel de colonnes parasites
df_final= df_final.drop(columns=["Unnamed: 0","No voie","No disposition","Surface reelle bati","code_insee","Code postal","Code departement","Code commune","altitude_maximale","superficie_hectare", "B/T/Q", "5eme lot", "Prefixe de section","No plan", "latitude_centre", "longitude_centre", "Surface Carrez du 1er lot", "Surface Carrez du 2eme lot", "Surface Carrez du 3eme lot", "Surface Carrez du 4eme lot", "Surface Carrez du 5eme lot"], errors="ignore")
df_final

,Valeur fonciere,Nombre de lots,Code type local,Nombre pieces principales,Surface terrain,population,densite,altitude_moyenne,altitude_minimale,latitude_mairie,longitude_mairie,surface_total,prixm2
100,105000.0,2,3.0,0.0,0.0,1211.0,49.0,253.0,222.0,46.157,5.146,64.01,1640.368692
101,105000.0,2,2.0,3.0,0.0,1211.0,49.0,253.0,222.0,46.157,5.146,64.01,1640.368692
118,309700.0,1,1.0,4.0,0.0,1916.0,95.0,286.0,225.0,45.920,4.882,81.46,3801.865946
125,565423.0,1,2.0,3.0,0.0,10137.0,300.0,810.0,464.0,46.358,6.136,85.82,6588.475880
130,110000.0,1,2.0,2.0,0.0,16295.0,1055.0,554.0,330.0,46.108,5.826,45.67,2408.583315
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999924,65000.0,1,2.0,1.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,34.38,1890.634090
999967,64500.0,1,2.0,1.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,21.91,2943.861251
999990,191450.0,1,2.0,3.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.73,3205.256990
999997,300000.0,2,2.0,2.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.23,5065.000844
999999,300000.0,2,3.0,0.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.23,5065.000844

In [67]:
# Definir le chemin de stockage du dataset final
data_dir = Path().resolve().parents[1]
data_path = data_dir /"Patricia-Promise-Immo"/"data"
processed_path = data_path/"processed" 
if not processed_path.exists():
    processed_path.mkdir(parents=True)

print(processed_path)

D:\ProjectFolderDevAI_2025-2026\Immo_project\Patricia-Promise-Immo\data\processed

In [68]:
df_final

,Valeur fonciere,Nombre de lots,Code type local,Nombre pieces principales,Surface terrain,population,densite,altitude_moyenne,altitude_minimale,latitude_mairie,longitude_mairie,surface_total,prixm2
100,105000.0,2,3.0,0.0,0.0,1211.0,49.0,253.0,222.0,46.157,5.146,64.01,1640.368692
101,105000.0,2,2.0,3.0,0.0,1211.0,49.0,253.0,222.0,46.157,5.146,64.01,1640.368692
118,309700.0,1,1.0,4.0,0.0,1916.0,95.0,286.0,225.0,45.920,4.882,81.46,3801.865946
125,565423.0,1,2.0,3.0,0.0,10137.0,300.0,810.0,464.0,46.358,6.136,85.82,6588.475880
130,110000.0,1,2.0,2.0,0.0,16295.0,1055.0,554.0,330.0,46.108,5.826,45.67,2408.583315
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999924,65000.0,1,2.0,1.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,34.38,1890.634090
999967,64500.0,1,2.0,1.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,21.91,2943.861251
999990,191450.0,1,2.0,3.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.73,3205.256990
999997,300000.0,2,2.0,2.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.23,5065.000844
999999,300000.0,2,3.0,0.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.23,5065.000844

In [69]:
df_final.describe()

,Valeur fonciere,Nombre de lots,Code type local,Nombre pieces principales,Surface terrain,population,densite,altitude_moyenne,altitude_minimale,latitude_mairie,longitude_mairie,surface_total,prixm2
count,9.542700e+04,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,95427.000000,9.542700e+04
mean,2.094304e+05,1.631970,2.439582,1.515211,2.832039,65123.991659,1602.569650,233.227818,128.792428,41.013581,3.994299,62.982578,3.737332e+03
std,3.115639e+05,0.810723,0.641684,1.574909,68.309946,97545.551134,1591.037262,369.001216,238.185380,13.430898,3.357037,68.612798,8.242548e+03
min,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-5.098000,0.930000,0.000000e+00
25%,9.600000e+04,1.000000,2.000000,0.000000,0.000000,5106.000000,247.000000,44.000000,0.000000,43.551000,1.371000,38.910000,1.851862e+03
50%,1.500000e+05,2.000000,2.000000,1.000000,0.000000,25815.000000,913.000000,115.000000,12.000000,43.882000,5.042000,57.540000,2.852697e+03
75%,2.375000e+05,2.000000,3.000000,3.000000,0.000000,73822.000000,2784.000000,260.000000,170.000000,47.221000,6.932000,75.140000,4.413982e+03
max,2.400000e+07,49.000000,4.000000,53.000000,8474.000000,504078.000000,5416.000000,2519.000000,1756.000000,50.136000,9.539000,6866.250000,1.678500e+06

In [70]:
df_final["Valeur fonciere"].describe()

count    9.542700e+04
mean     2.094304e+05
std      3.115639e+05
min      0.000000e+00
25%      9.600000e+04
50%      1.500000e+05
75%      2.375000e+05
max      2.400000e+07
Name: Valeur fonciere, dtype: float64

In [73]:
# Filtre des outlier sur la valeur foncière
df_final_filtre = df_final[(df_final["Valeur fonciere"] > 50000) & (df_final["Valeur fonciere"] <= 800000)]

#df_filtre = df_final[(df_final["Valeur fonciere"] > 50000) & (df_final["Valeur fonciere"] <= 800000)]
df_final_filtre

,Valeur fonciere,Nombre de lots,Code type local,Nombre pieces principales,Surface terrain,population,densite,altitude_moyenne,altitude_minimale,latitude_mairie,longitude_mairie,surface_total,prixm2
100,105000.0,2,3.0,0.0,0.0,1211.0,49.0,253.0,222.0,46.157,5.146,64.01,1640.368692
101,105000.0,2,2.0,3.0,0.0,1211.0,49.0,253.0,222.0,46.157,5.146,64.01,1640.368692
118,309700.0,1,1.0,4.0,0.0,1916.0,95.0,286.0,225.0,45.920,4.882,81.46,3801.865946
125,565423.0,1,2.0,3.0,0.0,10137.0,300.0,810.0,464.0,46.358,6.136,85.82,6588.475880
130,110000.0,1,2.0,2.0,0.0,16295.0,1055.0,554.0,330.0,46.108,5.826,45.67,2408.583315
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999924,65000.0,1,2.0,1.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,34.38,1890.634090
999967,64500.0,1,2.0,1.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,21.91,2943.861251
999990,191450.0,1,2.0,3.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.73,3205.256990
999997,300000.0,2,2.0,2.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.23,5065.000844
999999,300000.0,2,3.0,0.0,0.0,504078.0,4269.0,148.0,115.0,43.605,1.444,59.23,5065.000844

In [74]:
# Sauvegarde du dataset final en parquet

features_immo_data_path =processed_path/"features_immo_data.csv"
df_final_filtre.to_csv(features_immo_data_path, index= False)